nc: 80  # Number of classes
backbone:
  # Same backbone - creates proper pyramid
  - [-1, 1, QConv2D, {'in_channels': 3, 'out_channels': 64, 'kernel_size': 3, 'stride': 2, 'padding': 1}]  # 0-P1/2
  - [-1, 1, QConv2D, {'in_channels': 64, 'out_channels': 128, 'kernel_size': 3, 'stride': 2, 'padding': 1}]  # 1-P2/4
  - [-1, 1, C3k2, {'in_channels': 128, 'out_channels': 256, 'e': 0.25, 'c3k': False}]  # 2
  - [-1, 1, QConv2D, {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 2, 'padding': 1}]  # 3-P3/8
  - [-1, 1, C3k2, {'in_channels': 256, 'out_channels': 512, 'e': 0.25, 'c3k': False}]  # 4
  - [-1, 1, QConv2D, {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 2, 'padding': 1}]  # 5-P4/16
  - [-1, 1, C3k2, {'in_channels': 512, 'out_channels': 512, 'c3k': True}]  # 6
  - [-1, 1, QConv2D, {'in_channels': 512, 'out_channels': 1024, 'kernel_size': 3, 'stride': 2, 'padding': 1}]  # 7-P5/32
  - [-1, 1, C3k2, {'in_channels': 1024, 'out_channels': 1024, 'c3k': True}]  # 8
  - [-1, 2, SPPF, {'in_channels': 1024, 'out_channels': 1024}]  # 9
  - [-1, 1, C2PSA, {'in_channels': 1024, 'out_channels': 1024}]  # 10

head:
  - [-1, 1, QuaternionUpsample, {'scale_factor': 2, 'mode': 'nearest'}]
  - [[-1, 6], 1, QuaternionConcat,  {'dim': 1, 'reduce': True, 'target_channels': 512}] # cat backbone P4
  - [-1, 1, C3k2, {'in_channels': 512, 'out_channels': 512}] # 13

  - [-1, 1, QuaternionUpsample, {'scale_factor': 2, 'mode': 'nearest'}]
  - [[-1, 4], 1, QuaternionConcat, {'dim': 1, 'reduce': True, 'target_channels': 256}] # cat backbone P3
  - [-1, 1, C3k2, {'in_channels': 256, 'out_channels': 256}] # 16 p3/8

  - [-1, 1, QConv2D, {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 2, 'padding': 1}] 
  - [[-1, 13], 1, QuaternionConcat, {'dim': 1, 'reduce': True, 'target_channels': 512}] # cat head P4
  - [-1, 1, C3k2, {'in_channels': 512, 'out_channels': 512}] # 19 (P4/16-medium)

  - [-1, 1, QConv2D, {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 2, 'padding': 1}]
  - [[-1, 10], 1, QuaternionConcat, {'dim': 1, 'reduce': True, 'target_channels': 1024}] # cat head P5
  - [-1, 2, C3k2, {'in_channels': 1024, 'out_channels': 1024, 'c3k': True}] # 22 (P5/32-large)

  - [[16, 19, 22], 1, QDetectHead, {'nc': 80, 'ch': [256, 512, 1024], 'stride': [8, 16, 32]}]  # P3(H/8), P4(H/16), P5(H/32)