# configs/models/q_obb.yaml

nc: 80  # Number of classes
scales:
  n: [0.50, 0.25, 1024]
  s: [0.50, 0.50, 1024]
  m: [0.50, 1.00, 512]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.50, 512]

backbone:
  - [-1, 1, QConv2d, [in_channels=3, out_channels=64, kernel_size=3, stride=2]]
  - [-1, 1, QConv2d, [in_channels=64, out_channels=128, kernel_size=3, stride=2]]
  - [-1, 2, C3k2, [in_channels=128, out_channels=256, param=False, ratio=0.25]]
  - [-1, 1, QConv2d, [in_channels=256, out_channels=256, kernel_size=3, stride=2]]
  - [-1, 2, C3k2, [in_channels=256, out_channels=512, param=False, ratio=0.25]]
  - [-1, 1, QConv2d, [in_channels=512, out_channels=512, kernel_size=3, stride=2]]
  - [-1, 2, C3k2, [in_channels=512, out_channels=512, param=True]]
  - [-1, 1, QConv2d, [in_channels=512, out_channels=1024, kernel_size=3, stride=2]]
  - [-1, 2, C3k2, [in_channels=1024, out_channels=1024, param=True]]
  - [-1, 1, SPPF, [in_channels=1024, out_channels=1024, kernel_size=5]]
  - [-1, 2, C2PSA, [in_channels=1024, out_channels=1024]]

head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, QuaternionConcat, [1]]  # cat backbone P4
  - [-1, 2, C3k2, [in_channels=1024, out_channels=512, param=False]]

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, QuaternionConcat, [1]]  # cat backbone P3
  - [-1, 2, C3k2, [in_channels=512, out_channels=256, param=False]]

  - [-1, 1, QConv2d, [in_channels=256, out_channels=256, kernel_size=3, stride=2]]
  - [[-1, 13], 1, QuaternionConcat, [1]]  # cat head P4
  - [-1, 2, C3k2, [in_channels=512, out_channels=512, param=False]]

  - [-1, 1, QConv2d, [in_channels=512, out_channels=512, kernel_size=3, stride=2]]
  - [[-1, 10], 1, QuaternionConcat, [1]]  # cat head P5
  - [-1, 2, C3k2, [in_channels=1024, out_channels=512, param=True]]

  - [[16, 19, 22], 1, QOBBHead, [nc=80, param=1]]  # Detect(P3, P4, P5)
